DROP DATABASE ARMARINHODB;

CREATE DATABASE ARMARINHODB;

USE ARMARINHODB;

CREATE TABLE PRODUCT_TYPES (
    PRODUCT_TYPE_ID INT AUTO_INCREMENT NOT NULL,
    PRODUCT_TYPE_NAME VARCHAR (30) NOT NULL,
    PRIMARY KEY (PRODUCT_TYPE_ID)
);

CREATE TABLE PRODUCT_SIZES (
    PRODUCT_SIZE_ID INT AUTO_INCREMENT NOT NULL,
    PRODUCT_SIZE_NAME VARCHAR (2) NOT NULL,
    PRIMARY KEY (PRODUCT_SIZE_ID)
);

CREATE TABLE PRODUCT_COLORS (
	PRODUCT_COLOR_ID INT AUTO_INCREMENT NOT NULL,
    PRODUCT_COLOR_NAME VARCHAR (30) NOT NULL,
    PRIMARY KEY (PRODUCT_COLOR_ID)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT AUTO_INCREMENT NOT NULL,
    PRODUCT_NAME VARCHAR (30) NOT NULL,
    PRODUCT_PRICE DECIMAL (5,2) NOT NULL,
    PRODUCT_TYPE_FK INT NOT NULL,
    PRODUCT_SIZE_FK INT NOT NULL,
    PRODUCT_COLOR_FK INT NOT NULL,
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (PRODUCT_TYPE_FK) REFERENCES PRODUCT_TYPES (PRODUCT_TYPE_ID),
    FOREIGN KEY (PRODUCT_SIZE_FK) REFERENCES PRODUCT_SIZES (PRODUCT_SIZE_ID),
    FOREIGN KEY (PRODUCT_COLOR_FK) REFERENCES PRODUCT_COLORS (PRODUCT_COLOR_ID)
);

INSERT INTO PRODUCT_TYPES (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME) VALUES (DEFAULT, 'Vestido');
INSERT INTO PRODUCT_TYPES (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME) VALUES (DEFAULT, 'Shirt');
INSERT INTO PRODUCT_TYPES (PRODUCT_TYPE_ID, PRODUCT_TYPE_NAME) VALUES (DEFAULT, 'Pants');

INSERT INTO PRODUCT_SIZES (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME) VALUES (DEFAULT, 'P');
INSERT INTO PRODUCT_SIZES (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME) VALUES (DEFAULT, 'M');
INSERT INTO PRODUCT_SIZES (PRODUCT_SIZE_ID, PRODUCT_SIZE_NAME) VALUES (DEFAULT, 'G');

INSERT INTO PRODUCT_COLORS (PRODUCT_COLOR_ID, PRODUCT_COLOR_NAME) VALUES (DEFAULT, 'Green');
INSERT INTO PRODUCT_COLORS (PRODUCT_COLOR_ID, PRODUCT_COLOR_NAME) VALUES (DEFAULT, 'Red');
INSERT INTO PRODUCT_COLORS (PRODUCT_COLOR_ID, PRODUCT_COLOR_NAME) VALUES (DEFAULT, 'Black');

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE_FK, PRODUCT_SIZE_FK, PRODUCT_COLOR_FK) VALUES (DEFAULT, 'Vestido A', 10, 1, 1, 2);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE_FK, PRODUCT_SIZE_FK, PRODUCT_COLOR_FK) VALUES (DEFAULT, 'Shirt', 35, 2, 2, 3);
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE_FK, PRODUCT_SIZE_FK, PRODUCT_COLOR_FK) VALUES (DEFAULT, 'Pants', 7, 3, 3, 1);

SELECT * FROM PRODUCT_TYPES;
SELECT * FROM PRODUCT_SIZES;
SELECT * FROM PRODUCT_COLORS;
SELECT * FROM PRODUCTS;

SELECT * FROM PRODUCTS, PRODUCT_TYPES, PRODUCT_SIZES;
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE_NAME, PRODUCT_SIZE_NAME FROM PRODUCTS, PRODUCT_TYPES, PRODUCT_SIZES;

SELECT * FROM PRODUCTS INNER JOIN PRODUCT_TYPES, PRODUCT_SIZES;
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_TYPE_NAME, PRODUCT_SIZE_NAME FROM PRODUCTS INNER JOIN PRODUCT_TYPES, PRODUCT_SIZES;

SELECT * FROM PRODUCTS INNER JOIN PRODUCT_TYPES ON PRODUCTS.PRODUCT_TYPE_FK = PRODUCT_TYPES.PRODUCT_TYPE_ID;
SELECT * FROM PRODUCTS INNER JOIN PRODUCT_SIZES ON PRODUCTS.PRODUCT_SIZE_FK = PRODUCT_SIZES.PRODUCT_SIZE_ID;
SELECT * FROM PRODUCTS INNER JOIN PRODUCT_TYPES ON PRODUCTS.PRODUCT_TYPE_FK = PRODUCT_TYPES.PRODUCT_TYPE_ID INNER JOIN PRODUCT_SIZES ON PRODUCTS.PRODUCT_SIZE_FK = PRODUCT_SIZES.PRODUCT_SIZE_ID;

CREATE TABLE SALES (
	SALE_ID INT AUTO_INCREMENT NOT NULL,
    SALE_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (SALE_ID)
);

CREATE TABLE SALE_PRODUCTS (
	SALE_PRODUCT_ID INT AUTO_INCREMENT NOT NULL,
    SALE_FK INT NOT NULL,
    PRODUCT_FK INT NOT NULL,
    FOREIGN KEY (SALE_FK) REFERENCES SALES (SALE_ID),
    FOREIGN KEY (PRODUCT_FK) REFERENCES PRODUCTS (PRODUCT_ID),
    PRIMARY KEY (SALE_PRODUCT_ID)
);

USE ARMARINHODB;

SELECT * FROM SALES INNER JOIN PRODUCTS ON SALES.PRODUCT_FK = PRODUCTS.PRODUCT_ID;

INSERT INTO SALES (SALE_ID, SALE_DATE) VALUES (DEFAULT, NOW());
INSERT INTO SALES (SALE_ID, SALE_DATE) VALUES (DEFAULT, NOW());
INSERT INTO SALES (SALE_ID, SALE_DATE) VALUES (DEFAULT, NOW());

INSERT INTO SALES (SALE_ID, SALE_DATE, PRODUCT_FK) VALUES (DEFAULT, NOW());

DROP TABLE SALES;
DROP TABLE SALE_PRODUCTS;

SELECT * FROM SALE_PRODUCTS;

INSERT INTO SALE_PRODUCTS (SALE_PRODUCT_ID, SALE_FK, PRODUCT_FK) VALUES (DEFAULT, 1, 2);
INSERT INTO SALE_PRODUCTS (SALE_PRODUCT_ID, SALE_FK, PRODUCT_FK) VALUES (DEFAULT, 1, 1);
INSERT INTO SALE_PRODUCTS (SALE_PRODUCT_ID, SALE_FK, PRODUCT_FK) VALUES (DEFAULT, 1, 3);

INSERT INTO SALE_PRODUCTS (SALE_PRODUCT_ID, SALE_FK, PRODUCT_FK) VALUES (DEFAULT, 2, 3);
INSERT INTO SALE_PRODUCTS (SALE_PRODUCT_ID, SALE_FK, PRODUCT_FK) VALUES (DEFAULT, 2, 1);
